name = "JuliaGrid"
uuid = "040ba96c-7d3d-4d4a-931c-37903f53a565"
authors = ["Mirsad Cosovic <mirsad.cosovic@gmail.com>"]
version = "0.1.1"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
HDF5 = "0.17"
JuMP = "1.15"
OrderedCollections = "1"
LinearAlgebra = "<0.0.1, 1.8"
SparseArrays = "<0.0.1, 1.8"
SuiteSparse = "<0.0.1, 1.8"
Random = "<0.0.1, 1.8"
julia = "1.8"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HiGHS", "Ipopt", "GLPK", "Test"]