[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"

[compat]
Documenter = "1.0.0"
JuMP = "1.15.0"
HiGHS = "1.5.0"
Ipopt = "1.6.5"
GLPK = "1.1.3"